before_install:
- sudo mv /usr/bin/gpg /usr/bin/gpg1
- sudo update-alternatives --verbose --install /usr/bin/gpg gnupg /usr/bin/gpg2 50
- which gpg
- gpg --version
env:
- TRAVIS=true
install:
- python -m pip install --upgrade pip
- python -m pip install --editable .[dev]
language: python
python:
- "3.8.3"
script:
- make test
